repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version matching your devenv setup
    rev: v0.15.10
    hooks:
      - id: ruff-format
        types: [python]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0 # Use the latest stable version
    hooks:
      - id: no-commit-to-branch
        args: ["--branch", "main", "--branch", "master"]
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.0
    hooks:
      - id: gitleaks
  - repo: local
    hooks:
      - id: pip-audit
        name: pip-audit
        #ignore CVE-2025-69872 as not fixed
        entry: uv run --with pip-audit pip-audit  --ignore-vuln CVE-2025-69872
        language: system
        pass_filenames: false
        files: (^pyproject\.toml$|^uv\.lock$)

  - repo: https://github.com/jackdewinter/pymarkdown
    rev: v0.9.36
    hooks:
      - id: pymarkdown
        args:
          - "scan"
        exclude: ^ios/Runner/Assets\.xcassets/
