"""Features defined by soliplex"""

import pydantic
from haiku.rag.agents.chat import state as hr_chat_state
from haiku.rag.agents.research import models as hr_graph_models

FILTER_DOCUMENTS_FEATURE = "filter_documents"
ASK_HISTORY_FEATURE = "ask_history"
HAIKU_CHAT_FEATURE = hr_chat_state.AGUI_STATE_KEY

KW_ONLY_NONE = pydantic.Field(kw_only=True, default=None)


class FilterDocuments(pydantic.BaseModel):
    """Documents selected by the user to be used to answer a question

    This model describes the 'filter_documents' key in the AG-UI state.

    If 'document_ids' is empty or None, or if the 'filter_documents'
    key is not present in the AG-UI state, no filter is applied:  the
    'ask_with_rich_citations' tool will return all documents matching
    the query from the LLM.
    """

    document_ids: list[str] | None = KW_ONLY_NONE


class QuestionResponseCitations(pydantic.BaseModel):
    """Single question to the 'ask_with_rich_citations' tool

    Includes response generated by the tool and accompanying citations.
    """

    question: str
    response: str
    citations: list[hr_graph_models.Citation] = []


class AskedAndAnswered(pydantic.BaseModel):
    """History of questions asked and their replies + citations

    This model describes the 'ask_history' key in the AG-UI state.

    Each call to the 'ask_with_rich_citations' took append
    """

    questions: list[QuestionResponseCitations] = []
