services:
  # Production web server
  web:
    build:
      context: .
      dockerfile: Dockerfile
    # network_mode: "host" # only works on linux
    ports:
      - "9000:9000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  # Development environment with hot reload
  dev:
    image: ghcr.io/cirruslabs/flutter:3.37.0-0.1.pre
    working_dir: /app
    volumes:
      - ..:/app
    # network_mode: "host" # only works on linux
    ports:
      - "9000:9000"
    command: flutter run -d web-server --web-hostname=0.0.0.0 --web-port=9001
    extra_hosts:
      - "host.docker.internal:host-gateway"
    profiles:
      - dev
