"""soliplex-v0.53

Revision ID: 216d48e1e2e5
Revises: 4b63e5f3f39e
Create Date: 2026-03-23 15:07:07.706594

"""

import typing

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "216d48e1e2e5"
down_revision: str | typing.Sequence[str] | None = "4b63e5f3f39e"
branch_labels: str | typing.Sequence[str] | None = None
depends_on: str | typing.Sequence[str] | None = None


def upgrade(engine_name: str) -> None:
    """Upgrade schema."""
    globals()[f"upgrade_{engine_name}"]()


def downgrade(engine_name: str) -> None:
    """Downgrade schema."""
    globals()[f"downgrade_{engine_name}"]()


def upgrade_agui() -> None:
    """Upgrade agui schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "review_history", sa.Column("user_name", sa.String(), nullable=True)
    )
    op.add_column(
        "review_history", sa.Column("email", sa.String(), nullable=True)
    )
    op.add_column("thread", sa.Column("email", sa.String(), nullable=True))
    op.create_index(op.f("ix_thread_email"), "thread", ["email"], unique=False)
    # ### end Alembic commands ###


def downgrade_agui() -> None:
    """Downgrade agui schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_thread_email"), table_name="thread")
    op.drop_column("thread", "email")
    op.drop_column("review_history", "email")
    op.drop_column("review_history", "user_name")
    # ### end Alembic commands ###


def upgrade_authz() -> None:
    """Upgrade authz schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_authz() -> None:
    """Downgrade authz schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
