"""soliplex-v0.51.1

Revision ID: 4b63e5f3f39e
Revises: d5009d4f9874
Create Date: 2026-03-18 19:00:25.767373

"""

import typing

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4b63e5f3f39e"
down_revision: typing.Union[str, typing.Sequence[str], None] = "d5009d4f9874"
branch_labels: typing.Union[str, typing.Sequence[str], None] = None
depends_on: typing.Union[str, typing.Sequence[str], None] = None


def upgrade(engine_name: str) -> None:
    """Upgrade schema."""
    globals()[f"upgrade_{engine_name}"]()


def downgrade(engine_name: str) -> None:
    """Downgrade schema."""
    globals()[f"downgrade_{engine_name}"]()


def upgrade_agui() -> None:
    """Upgrade agui schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "review_history",
        sa.Column("id_", sa.Integer(), nullable=False),
        sa.Column("created", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("run_feedback_id_", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("REVIEWED", "RESOLVED", name="feedbackreviewstatus"),
            nullable=True,
        ),
        sa.Column("note", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_feedback_id_"],
            ["run_feedback.id_"],
            name=op.f("fk_review_history_run_feedback_id__run_feedback"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id_", name=op.f("pk_review_history")),
    )
    # ### end Alembic commands ###


def downgrade_agui() -> None:
    """Downgrade agui schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("review_history")
    # ### end Alembic commands ###


def upgrade_authz() -> None:
    """Upgrade authz schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_authz() -> None:
    """Downgrade authz schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
