"""soliplex-v0.67

Revision ID: 63edaa5987f6
Revises: 216d48e1e2e5
Create Date: 2026-05-26 12:35:42.900708

"""

import json
import re
import typing

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "63edaa5987f6"
down_revision: str | typing.Sequence[str] | None = "216d48e1e2e5"
branch_labels: str | typing.Sequence[str] | None = None
depends_on: str | typing.Sequence[str] | None = None


# Conversion format frozen at this revision so replaying history never
# depends on live app code. Mirrors authz.token_field_json_path as of
# v0.67; _LEGACY_FIELD_RES is its inverse.
def _token_field_json_path(field: str, value: str) -> str:
    return f"$[?$.{field} == {json.dumps(value)}]"


_LEGACY_FIELD_RES = {
    field: re.compile(rf"^\$\[\?\$\.{field} == (?P<value>.+)\]$")
    for field in ("preferred_username", "email")
}


def _acl_entries_table() -> sa.Table:
    return sa.table(
        "room_acl_entries",
        sa.column("id_", sa.Integer),
        sa.column("preferred_username", sa.String),
        sa.column("email", sa.String),
        sa.column("json_path", sa.String),
    )


def upgrade(engine_name: str) -> None:
    """Upgrade schema."""
    globals()[f"upgrade_{engine_name}"]()


def downgrade(engine_name: str) -> None:
    """Downgrade schema."""
    globals()[f"downgrade_{engine_name}"]()


def upgrade_agui() -> None:
    """Upgrade agui schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_agui() -> None:
    """Downgrade agui schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_authz() -> None:
    """Upgrade authz schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "room_acl_entries", sa.Column("json_path", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###
    _convert_legacy_discriminators()
    op.drop_column("room_acl_entries", "preferred_username")
    op.drop_column("room_acl_entries", "email")


def downgrade_authz() -> None:
    """Downgrade authz schema."""
    op.add_column(
        "room_acl_entries",
        sa.Column("preferred_username", sa.String(), nullable=True),
    )
    op.add_column(
        "room_acl_entries", sa.Column("email", sa.String(), nullable=True)
    )
    _restore_legacy_discriminators()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("room_acl_entries", "json_path")
    # ### end Alembic commands ###


def _convert_legacy_discriminators() -> None:
    """Translate preferred_username / email discriminators to json_path.

    The legacy columns are cleared once converted. 'check_token'
    evaluates 'json_path' ahead of those columns, so a converted entry
    keeps matching the same tokens. Entries that already carry an
    explicit 'json_path' are left untouched.
    """
    acl = _acl_entries_table()
    bind = op.get_bind()
    rows = bind.execute(
        sa.select(acl.c.id_, acl.c.preferred_username, acl.c.email).where(
            acl.c.json_path.is_(None),
            sa.or_(
                acl.c.preferred_username.is_not(None),
                acl.c.email.is_not(None),
            ),
        )
    ).all()
    for row in rows:
        if row.preferred_username is not None:
            json_path = _token_field_json_path(
                "preferred_username", row.preferred_username
            )
        else:
            json_path = _token_field_json_path("email", row.email)
        bind.execute(
            sa.update(acl)
            .where(acl.c.id_ == row.id_)
            .values(
                json_path=json_path,
                preferred_username=None,
                email=None,
            )
        )


def _restore_legacy_discriminators() -> None:
    """Reverse _convert_legacy_discriminators before dropping json_path.

    Only json_path values matching the converted-discriminator shape are
    restored. Genuine '--json-path' entries cannot be represented by the
    legacy columns and are dropped along with the column.
    """
    acl = _acl_entries_table()
    bind = op.get_bind()
    rows = bind.execute(
        sa.select(acl.c.id_, acl.c.json_path).where(
            acl.c.json_path.is_not(None)
        )
    ).all()
    for row in rows:
        for field, pattern in _LEGACY_FIELD_RES.items():
            match = pattern.match(row.json_path)
            if match is not None:
                bind.execute(
                    sa.update(acl)
                    .where(acl.c.id_ == row.id_)
                    .values(**{field: json.loads(match.group("value"))})
                )
                break
