"""soliplex-v0.76

Revision ID: 98cd91f27cb5
Revises: 63edaa5987f6
Create Date: 2026-08-14 17:30:32.840043

"""

import typing

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "98cd91f27cb5"
down_revision: str | typing.Sequence[str] | None = "63edaa5987f6"
branch_labels: str | typing.Sequence[str] | None = None
depends_on: str | typing.Sequence[str] | None = None


def upgrade(engine_name: str) -> None:
    """Upgrade schema."""
    globals()[f"upgrade_{engine_name}"]()


def downgrade(engine_name: str) -> None:
    """Downgrade schema."""
    globals()[f"downgrade_{engine_name}"]()


def upgrade_agui() -> None:
    """Upgrade agui schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "label",
        sa.Column("id_", sa.Integer(), nullable=False),
        sa.Column("created", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("name_key", sa.String(), nullable=False),
        sa.Column("color", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id_", name=op.f("pk_label")),
        sa.UniqueConstraint("name_key", name=op.f("uq_label_name_key")),
        # Matches 'Label.__table_args__': without it SQLite reuses
        # 'max(id) + 1', so a new label can inherit a deleted one's ID
        # and any stale client catalogue would then paint the wrong chip.
        sqlite_autoincrement=True,
    )
    op.create_table(
        "thread_label",
        sa.Column("thread_id_", sa.Integer(), nullable=False),
        sa.Column("label_id_", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["label_id_"],
            ["label.id_"],
            name=op.f("fk_thread_label_label_id__label"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["thread_id_"],
            ["thread.id_"],
            name=op.f("fk_thread_label_thread_id__thread"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "thread_id_", "label_id_", name=op.f("pk_thread_label")
        ),
    )
    op.create_index(
        op.f("ix_thread_label_label_id_"),
        "thread_label",
        ["label_id_"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade_agui() -> None:
    """Downgrade agui schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_thread_label_label_id_"), table_name="thread_label")
    op.drop_table("thread_label")
    op.drop_table("label")
    # ### end Alembic commands ###


def upgrade_authz() -> None:
    """Upgrade authz schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_authz() -> None:
    """Downgrade authz schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
