"""soliplex_v_0_44

Revision ID: d5009d4f9874
Revises:
Create Date: 2026-02-24 18:23:44.304011

"""

import typing

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d5009d4f9874"
down_revision: str | typing.Sequence[str] | None = None
branch_labels: str | typing.Sequence[str] | None = None
depends_on: str | typing.Sequence[str] | None = None


def upgrade(engine_name: str) -> None:
    """Upgrade schema."""
    globals()[f"upgrade_{engine_name}"]()


def downgrade(engine_name: str) -> None:
    """Downgrade schema."""
    globals()[f"downgrade_{engine_name}"]()


def upgrade_agui() -> None:
    """Upgrade agui schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "thread",
        sa.Column("id_", sa.Integer(), nullable=False),
        sa.Column("thread_id", sa.String(), nullable=False),
        sa.Column("room_id", sa.String(), nullable=False),
        sa.Column("created", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("user_name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id_", name=op.f("pk_thread")),
    )
    op.create_index(
        op.f("ix_thread_room_id"), "thread", ["room_id"], unique=False
    )
    op.create_index(
        op.f("ix_thread_thread_id"), "thread", ["thread_id"], unique=False
    )
    op.create_index(
        op.f("ix_thread_user_name"), "thread", ["user_name"], unique=False
    )
    op.create_table(
        "run",
        sa.Column("id_", sa.Integer(), nullable=False),
        sa.Column("thread_id_", sa.Integer(), nullable=False),
        sa.Column("parent_id_", sa.Integer(), nullable=True),
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("created", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("finished", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id_"],
            ["run.id_"],
            name=op.f("fk_run_parent_id__run"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["thread_id_"],
            ["thread.id_"],
            name=op.f("fk_run_thread_id__thread"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id_", name=op.f("pk_run")),
    )
    op.create_index(op.f("ix_run_run_id"), "run", ["run_id"], unique=False)
    op.create_table(
        "thread_metadata",
        sa.Column("id_", sa.Integer(), nullable=False),
        sa.Column("created", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("thread_id_", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["thread_id_"],
            ["thread.id_"],
            name=op.f("fk_thread_metadata_thread_id__thread"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id_", name=op.f("pk_thread_metadata")),
    )
    op.create_table(
        "run_agent_input",
        sa.Column("id_", sa.Integer(), nullable=False),
        sa.Column("created", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("run_id_", sa.Integer(), nullable=True),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id_"],
            ["run.id_"],
            name=op.f("fk_run_agent_input_run_id__run"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id_", name=op.f("pk_run_agent_input")),
    )
    op.create_table(
        "run_event",
        sa.Column("id_", sa.Integer(), nullable=False),
        sa.Column("created", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("run_id_", sa.Integer(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id_"],
            ["run.id_"],
            name=op.f("fk_run_event_run_id__run"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id_", name=op.f("pk_run_event")),
    )
    op.create_table(
        "run_feedback",
        sa.Column("id_", sa.Integer(), nullable=False),
        sa.Column("created", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("run_id_", sa.Integer(), nullable=False),
        sa.Column("feedback", sa.String(), nullable=False),
        sa.Column("reason", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id_"],
            ["run.id_"],
            name=op.f("fk_run_feedback_run_id__run"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id_", name=op.f("pk_run_feedback")),
    )
    op.create_table(
        "run_metadata",
        sa.Column("id_", sa.Integer(), nullable=False),
        sa.Column("created", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("run_id_", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id_"],
            ["run.id_"],
            name=op.f("fk_run_metadata_run_id__run"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id_", name=op.f("pk_run_metadata")),
    )
    op.create_table(
        "run_usage",
        sa.Column("id_", sa.Integer(), nullable=False),
        sa.Column("created", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("run_id_", sa.Integer(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("requests", sa.Integer(), nullable=False),
        sa.Column("tool_calls", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id_"],
            ["run.id_"],
            name=op.f("fk_run_usage_run_id__run"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id_", name=op.f("pk_run_usage")),
    )
    # ### end Alembic commands ###


def downgrade_agui() -> None:
    """Downgrade agui schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("run_usage")
    op.drop_table("run_metadata")
    op.drop_table("run_feedback")
    op.drop_table("run_event")
    op.drop_table("run_agent_input")
    op.drop_table("thread_metadata")
    op.drop_index(op.f("ix_run_run_id"), table_name="run")
    op.drop_table("run")
    op.drop_index(op.f("ix_thread_user_name"), table_name="thread")
    op.drop_index(op.f("ix_thread_thread_id"), table_name="thread")
    op.drop_index(op.f("ix_thread_room_id"), table_name="thread")
    op.drop_table("thread")
    # ### end Alembic commands ###


def upgrade_authz() -> None:
    """Upgrade authz schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_users",
        sa.Column("id_", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("created", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id_", name=op.f("pk_admin_users")),
        sa.UniqueConstraint("email", name=op.f("uq_admin_users_email")),
    )
    op.create_table(
        "room_policies",
        sa.Column("id_", sa.Integer(), nullable=False),
        sa.Column("room_id", sa.String(), nullable=False),
        sa.Column("created", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column(
            "default_allow_deny",
            sa.Enum("ALLOW", "DENY", name="allowdeny"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id_", name=op.f("pk_room_policies")),
        sa.UniqueConstraint("room_id", name=op.f("uq_room_policies_room_id")),
    )
    op.create_table(
        "room_acl_entries",
        sa.Column("id_", sa.Integer(), nullable=False),
        sa.Column("room_policy_id_", sa.Integer(), nullable=False),
        sa.Column("created", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column(
            "allow_deny",
            sa.Enum("ALLOW", "DENY", name="allowdeny"),
            nullable=False,
        ),
        sa.Column("everyone", sa.Boolean(), nullable=False),
        sa.Column("authenticated", sa.Boolean(), nullable=False),
        sa.Column("preferred_username", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["room_policy_id_"],
            ["room_policies.id_"],
            name=op.f("fk_room_acl_entries_room_policy_id__room_policies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id_", name=op.f("pk_room_acl_entries")),
    )
    # ### end Alembic commands ###


def downgrade_authz() -> None:
    """Downgrade authz schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("room_acl_entries")
    op.drop_table("room_policies")
    op.drop_table("admin_users")
    # ### end Alembic commands ###
