// Generated code from quicktype - ignoring style issues
// ignore_for_file: sort_constructors_first
// ignore_for_file: prefer_single_quotes
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: unnecessary_ignore

// To parse this JSON data, do
//
//     final askHistory = askHistoryFromJson(jsonString);

import 'dart:convert';

AskHistory askHistoryFromJson(String str) =>
    AskHistory.fromJson(json.decode(str));

String askHistoryToJson(AskHistory data) => json.encode(data.toJson());

///History of questions asked and their replies + citations
///
///This model describes the 'ask_history' key in the AG-UI state.
///
///Each call to the 'ask_with_rich_citations' took append
class AskHistory {
  final List<QuestionResponseCitations>? questions;

  AskHistory({
    this.questions,
  });

  factory AskHistory.fromJson(Map<String, dynamic> json) => AskHistory(
    questions: json["questions"] == null
        ? []
        : List<QuestionResponseCitations>.from(
            json["questions"]!.map(
              (x) => QuestionResponseCitations.fromJson(x),
            ),
          ),
  );

  Map<String, dynamic> toJson() => {
    "questions": questions == null
        ? []
        : List<dynamic>.from(questions!.map((x) => x.toJson())),
  };
}

///Single question to the 'ask_with_rich_citations' tool
///
///Includes response generated by the tool and accompanying citations.
class QuestionResponseCitations {
  final List<Citation>? citations;
  final String question;
  final String response;

  QuestionResponseCitations({
    this.citations,
    required this.question,
    required this.response,
  });

  factory QuestionResponseCitations.fromJson(Map<String, dynamic> json) =>
      QuestionResponseCitations(
        citations: json["citations"] == null
            ? []
            : List<Citation>.from(
                json["citations"]!.map((x) => Citation.fromJson(x)),
              ),
        question: json["question"],
        response: json["response"],
      );

  Map<String, dynamic> toJson() => {
    "citations": citations == null
        ? []
        : List<dynamic>.from(citations!.map((x) => x.toJson())),
    "question": question,
    "response": response,
  };
}

///Resolved citation with full metadata for display/visual grounding.
class Citation {
  final String chunkId;
  final String content;
  final String documentId;
  final String? documentTitle;
  final String documentUri;
  final List<String>? headings;
  final List<int>? pageNumbers;

  Citation({
    required this.chunkId,
    required this.content,
    required this.documentId,
    this.documentTitle,
    required this.documentUri,
    this.headings,
    this.pageNumbers,
  });

  factory Citation.fromJson(Map<String, dynamic> json) => Citation(
    chunkId: json["chunk_id"],
    content: json["content"],
    documentId: json["document_id"],
    documentTitle: json["document_title"],
    documentUri: json["document_uri"],
    headings: json["headings"] == null
        ? []
        : List<String>.from(json["headings"]!.map((x) => x)),
    pageNumbers: json["page_numbers"] == null
        ? []
        : List<int>.from(json["page_numbers"]!.map((x) => x)),
  );

  Map<String, dynamic> toJson() => {
    "chunk_id": chunkId,
    "content": content,
    "document_id": documentId,
    "document_title": documentTitle,
    "document_uri": documentUri,
    "headings": headings == null
        ? []
        : List<dynamic>.from(headings!.map((x) => x)),
    "page_numbers": pageNumbers == null
        ? []
        : List<dynamic>.from(pageNumbers!.map((x) => x)),
  };
}
