// To parse this JSON data, do
//
//     final askHistory = askHistoryFromJson(jsonString);

import 'dart:convert';

AskHistory askHistoryFromJson(String str) =>
    AskHistory.fromJson(json.decode(str) as Map<String, dynamic>);

String askHistoryToJson(AskHistory data) => json.encode(data.toJson());


/// History of questions asked and their replies + citations
///
/// This model describes the 'ask_history' key in the AG-UI state.
///
/// Each call to the 'ask_with_rich_citations' took append
class AskHistory {
  AskHistory({
    this.questions,
  });

  factory AskHistory.fromJson(Map<String, dynamic> json) => AskHistory(
        questions: json['questions'] == null
            ? []
            : List<QuestionResponseCitations>.from(
                (json['questions']! as List<dynamic>).map(
                  (x) => QuestionResponseCitations.fromJson(
                      x as Map<String, dynamic>),
                ),
              ),
      );

  final List<QuestionResponseCitations>? questions;

  Map<String, dynamic> toJson() => {
        'questions': questions == null
            ? []
            : List<dynamic>.from(questions!.map((x) => x.toJson())),
      };
}


/// Single question to the 'ask_with_rich_citations' tool
///
/// Includes response generated by the tool and accompanying citations.
class QuestionResponseCitations {
  QuestionResponseCitations({
    required this.question,
    required this.response,
    this.citations,
  });

  factory QuestionResponseCitations.fromJson(Map<String, dynamic> json) =>
      QuestionResponseCitations(
        question: json['question'] as String,
        response: json['response'] as String,
        citations: json['citations'] == null
            ? []
            : List<Citation>.from(
                (json['citations']! as List<dynamic>).map(
                  (x) => Citation.fromJson(x as Map<String, dynamic>),
                ),
              ),
      );

  final String question;
  final String response;
  final List<Citation>? citations;

  Map<String, dynamic> toJson() => {
        'citations': citations == null
            ? []
            : List<dynamic>.from(citations!.map((x) => x.toJson())),
        'question': question,
        'response': response,
      };
}


/// Resolved citation with full metadata for display/visual grounding.
class Citation {
  Citation({
    required this.chunkId,
    required this.content,
    required this.documentId,
    required this.documentUri,
    this.documentTitle,
    this.headings,
    this.pageNumbers,
  });

  factory Citation.fromJson(Map<String, dynamic> json) => Citation(
        chunkId: json['chunk_id'] as String,
        content: json['content'] as String,
        documentId: json['document_id'] as String,
        documentUri: json['document_uri'] as String,
        documentTitle: json['document_title'] as String?,
        headings: json['headings'] == null
            ? []
            : List<String>.from(
                (json['headings']! as List<dynamic>).map((x) => x as String),
              ),
        pageNumbers: json['page_numbers'] == null
            ? []
            : List<int>.from(
                (json['page_numbers']! as List<dynamic>).map((x) => x as int),
              ),
      );

  final String chunkId;
  final String content;
  final String documentId;
  final String documentUri;
  final String? documentTitle;
  final List<String>? headings;
  final List<int>? pageNumbers;

  Map<String, dynamic> toJson() => {
        'chunk_id': chunkId,
        'content': content,
        'document_id': documentId,
        'document_title': documentTitle,
        'document_uri': documentUri,
        'headings': headings == null
            ? []
            : List<dynamic>.from(headings!.map((x) => x)),
        'page_numbers': pageNumbers == null
            ? []
            : List<dynamic>.from(pageNumbers!.map((x) => x)),
      };
}
